### ISSUE TITLE
<class 'tuple'> to Tensor Error

### ISSUE THREAD

**Issue by HoudaJebbari** [ShahinSHH/COVID-FACT#3]
First of all, I want to thank you for the code provided and the effort put into it.
I have encountered the reshape problem that was already raised as an issue, so I followed your proposed fix and downgraded the version of keras and tensorflow to those mentioned in the README (tensorflow 1.14.0 and keras 2.2.4), however another problem was raised when instantiating the 'Capsule' class, the problem is as follows:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    557     try:
--> 558       str_values = [compat.as_bytes(x) for x in proto_values]
    559     except TypeError:

26 frames
TypeError: Expected binary or unicode string, got 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    560       raise TypeError("Failed to convert object of type %s to Tensor. "
    561                       "Contents: %s. Consider casting elements to a "
--> 562                       "supported type." % (type(values), values))
    563     tensor_proto.string_val.extend(str_values)
    564     return tensor_proto

TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (1, Dimension(128), 512). Consider casting elements to a supported type.
```

**Comment by ShahinSHH** [comment]
Hi Houda,
I encountered the same issue when using my other system but downgrading the tensorflow and keras versions and using tensorflow.keras instead of keras resolved the issue for me. Have you tried replacing keras with tensorflow.keras in the very beginning of the code (in the import lines)?

**Comment by HoudaJebbari** [comment]
Thank you for your response.
I have already replaced all the keras import lines with tensorflow.keras but the problem persists.

**Comment by HoudaJebbari** [comment]
I actually tried it on google colab, do you think it could cause a problem or do you have an idea about this?
